=== EdwardOst/demo-template/ping/arin_schema1.xsd
<?xml version="1.0" encoding="utf-8"?><xs:schema xmlns:tns="http://twt.demo.se.talend.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" targetNamespace="http://twt.demo.se.talend.com/" version="1.0">
    <xs:element name="address" type="tns:Address"/>
    <xs:element name="netblock" type="tns:NetBlock"/>
    <xs:element name="network" type="tns:Network"/>
    <xs:element name="org" type="tns:Org"/>
    <xs:element name="ping" type="tns:ping"/>
    <xs:element name="pingResponse" type="tns:pingResponse"/>
    <xs:element name="pingResult" type="tns:PingResult"/>
    <xs:element name="whoIs" type="tns:WhoIs"/>
    <xs:complexType name="ping">
        <xs:sequence>
            <xs:element name="ipAddress" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="pingResponse">
        <xs:sequence>
            <xs:element minOccurs="0" ref="tns:whoIs"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="WhoIs">
        <xs:sequence>
            <xs:element name="network" nillable="true" type="tns:Network"/>
            <xs:element name="org" nillable="true" type="tns:Org"/>
        </xs:sequence>
        <xs:attribute name="ip" type="xs:string" use="required"/>
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="Network">
        <xs:sequence>
            <xs:element name="netblocks" nillable="true">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="netblock" nillable="true" type="tns:NetBlock"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="NetBlock">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="pingResult" nillable="true" type="tns:PingResult"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PingResult">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="host" type="xs:string"/>
                <xs:attribute name="returnValue" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="Org">
        <xs:sequence>
            <xs:element name="address" nillable="true" type="tns:Address"/>
        </xs:sequence>
        <xs:attribute name="handle" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="Address">
        <xs:sequence>
            <xs:element name="city" nillable="true" type="xs:string"/>
            <xs:element name="state" nillable="true" type="xs:string"/>
            <xs:element name="zip" nillable="true" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== EdwardOst/demo-template/helloworld/src/main/java/com/talend/se/demo/twt/exampleWhoIs.xml
<?xml version="1.0" encoding="UTF-8"?>
<twt:whoIs ip="96.241.55.231" ref="http://whois.arin.net/rest/net/NET-96-224-0-0-1"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:twt='http://twt.demo.se.talend.com/'
    xsi:schemaLocation='http://twt.demo.se.talend.com/ C:/Users/eost/Documents/netbeans/ping/src/com/talend/se/demo/twt/arin_schema1.xsd'>

    <netblocks>
        <netblock>
            <pingResult  host="96.224.0.0" returnValue="1">Pinging 96.224.0.0 with 32 bytes of data:Request timed out.Request timed out.Request timed out.Ping statistics for 96.224.0.0:    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss),</pingResult>
            <pingResult  host="96.224.0.1" returnValue="1">Pinging 96.224.0.1 with 32 bytes of data:Request timed out.Request timed out.Request timed out.Ping statistics for 96.224.0.1:    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss),</pingResult>
            <pingResult  host="96.224.0.2" returnValue="0">Pinging 96.224.0.2 with 32 bytes of data:Reply from 96.224.0.2: bytes=32 time=52ms TTL=56Reply from 96.224.0.2: bytes=32 time=54ms TTL=56Reply from 96.224.0.2: bytes=32 time=55ms TTL=56Ping statistics for 96.224.0.2:    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),Approximate round trip times in milli-seconds:    Minimum = 52ms, Maximum = 55ms, Average = 53ms</pingResult>
            <pingResult  host="96.224.0.3" returnValue="0">Pinging 96.224.0.3 with 32 bytes of data:Reply from 96.224.0.3: bytes=32 time=48ms TTL=56Reply from 96.224.0.3: bytes=32 time=50ms TTL=56Reply from 96.224.0.3: bytes=32 time=50ms TTL=56Ping statistics for 96.224.0.3:    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),Approximate round trip times in milli-seconds:    Minimum = 48ms, Maximum = 50ms, Average = 49ms</pingResult>
            <pingResult  host="96.224.0.4" returnValue="0">Pinging 96.224.0.4 with 32 bytes of data:Reply from 96.224.0.4: bytes=32 time=55ms TTL=56Reply from 96.224.0.4: bytes=32 time=57ms TTL=56Reply from 96.224.0.4: bytes=32 time=59ms TTL=56Ping statistics for 96.224.0.4:    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),Approximate round trip times in milli-seconds:    Minimum = 55ms, Maximum = 59ms, Average = 57ms</pingResult>
        </netblock>
        <netblock>
            <pingResult  host="96.224.0.0" returnValue="1">Pinging 96.224.0.0 with 32 bytes of data:Request timed out.Request timed out.Request timed out.Ping statistics for 96.224.0.0:    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss),</pingResult>
            <pingResult  host="96.224.0.1" returnValue="1">Pinging 96.224.0.1 with 32 bytes of data:Request timed out.Request timed out.Request timed out.Ping statistics for 96.224.0.1:    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss),</pingResult>
            <pingResult  host="96.224.0.2" returnValue="0">Pinging 96.224.0.2 with 32 bytes of data:Reply from 96.224.0.2: bytes=32 time=52ms TTL=56Reply from 96.224.0.2: bytes=32 time=54ms TTL=56Reply from 96.224.0.2: bytes=32 time=55ms TTL=56Ping statistics for 96.224.0.2:    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),Approximate round trip times in milli-seconds:    Minimum = 52ms, Maximum = 55ms, Average = 53ms</pingResult>
            <pingResult  host="96.224.0.3" returnValue="0">Pinging 96.224.0.3 with 32 bytes of data:Reply from 96.224.0.3: bytes=32 time=48ms TTL=56Reply from 96.224.0.3: bytes=32 time=50ms TTL=56Reply from 96.224.0.3: bytes=32 time=50ms TTL=56Ping statistics for 96.224.0.3:    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),Approximate round trip times in milli-seconds:    Minimum = 48ms, Maximum = 50ms, Average = 49ms</pingResult>
            <pingResult  host="96.224.0.4" returnValue="0">Pinging 96.224.0.4 with 32 bytes of data:Reply from 96.224.0.4: bytes=32 time=55ms TTL=56Reply from 96.224.0.4: bytes=32 time=57ms TTL=56Reply from 96.224.0.4: bytes=32 time=59ms TTL=56Ping statistics for 96.224.0.4:    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),Approximate round trip times in milli-seconds:    Minimum = 55ms, Maximum = 59ms, Average = 57ms</pingResult>
        </netblock>
    </netblocks>
    
    <org handle="VRIS" ref="http://whois.arin.net/rest/org/VRIS" name="Verizon Online LLC">
        <address>
            <city>Ashburn</city>
            <state>VA</state>
            <zip>20147</zip>
        </address>
    </org>
</twt:whoIs>
